apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: gateway-api-crds
name: gateway-api-crds
repo: https://wiremind.github.io/wiremind-helm-charts
chartHome: ../../../../../charts
releaseName: gateway-api-crds
namespace: kube-system
includeCRDs: true
skipHooks: false
version: 1.4.0