apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/kgateway/
  - kgateway-http.yaml
generators:
  - ../../../../../helm/overlays/dev/cluster/kgateway/