apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-http
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
