apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kgateway
name: kgateway
repo: oci://cr.kgateway.dev/kgateway-dev/charts
chartHome: ../../../../../charts
releaseName: kgateway
namespace: kgateway-system
includeCRDs: true
skipHooks: false
version: v2.1.2